export const colors = {
  primary:        '#0D1B2A',
  accent:         '#F4801A',
  white:          '#FFFFFF',
  background:     '#F4F5F7',
  card:           '#FFFFFF',
  border:         '#EEEEEE',
  textDark:       '#111111',
  textMid:        '#333333',
  textMuted:      '#888888',
  textLight:      '#AAAAAA',
  imgPlaceholder: '#E8EAF0',
  success:        '#22C55E',
  warning:        '#F59E0B',
  danger:         '#EF4444',
};
